version: '2'
services:
  3005be:
    container_name: 3005be
    build: ./backend
    image: 3005be
    restart: always
    ports:
      - '9756:80'
    volumes:
      - './data/backend:/data:z'
  3005fe:
    container_name: 3005fe
    build: ./frontend
    image: 3005fe
    restart: always
    ports:
      - '9757:3000'

